<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "xptmp"
 *
 * Auto generated by Extension Builder 2014-09-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'xp Fluid Template',
	'description' => 'It creats the base template in Fluid for the TYPO3, just include the typoscript',
	'category' => 'templates',
	'author' => 'Xiaoling Peng',
	'author_email' => 'pengmaradi@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);